version: "3.1"

services:
  bug-tracker:
    build:
      context: .
      dockerfile: Dockerfile
      target: build  # name of the Dockerfile build step
    command: npm run start:dev
    env_file: .env.development
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app/bug-tracker

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:jammy
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb

volumes:
  mongodb_data:
