export const TASK_TYPES = ({
  FEATURE: 'FEATURE',
  BUG: 'BUG',
}) as const;

export const TASK_STATUS = ({
  UNDER_CONSTRUCTION: 'UNDER_CONSTRUCTION',
  IN_REVIEW: 'IN_REVIEW',
  IN_PROGRESS: 'IN_PROGRESS',
  FINISHED: 'FINISHED',
  CLOSED: 'CLOSED',
}) as const;

export const TASK_SEVERITY = ({
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
  EXTREMELY_HIGH: 'EXTREMELY_HIGH',
}) as const;

export const TASK_PRIORITY = ({
  LOW: 'LOW',
  NORMAL: 'NORMAL',
  HIGH: 'HIGH',
  EXTREMELY_HIGH: 'EXTREMELY_HIGH',
}) as const;
