export const PERMISSION_ACTION = ({
  GET: 'GET',
  LIST: 'LIST',
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  DELETE_LINK: 'DELETE_LINK',
  CREATE_LINK: 'CREATE_LINK',
}) as const;

export const PERMISSION_RESOURCE = ({
  PERMISSION: 'PERMISSION',
  ROLE: 'ROLE',
  TASK: 'TASK',
  BUG: 'BUG',
  FEATURE: 'FEATURE',
  PROJECT: 'PROJECT',
  USER: 'USER',
  FILE: 'FILE',
  TASK_COMMENT: 'TASK_COMMENT',
  BUG_COMMENT: 'BUG_COMMENT',
  FEATURE_COMMENT: 'FEATURE_COMMENT',
  TASK_LOG: 'TASK_LOG',
}) as const;
